### ISSUE TITLE
Thank you for your contribution. After 20 rounds of training on scenefrlow, and then fine-tuning 20 rounds, is it still not convergence? I added some extra epochs, and the EPE will be lower than 0.64

### ISSUE THREAD

**Issue by 1434205229** [gangweiX/ICG-Stereo#5]

**Comment by gangweix** [comment]
Yes, more training epochs can bring better results.

**Comment by 1434205229** [comment]
thank you

**Comment by flyxuexi** [comment]
> thank you

哥，请问你训练的环境和作者完全一样吗，谢谢

**Comment by 1434205229** [comment]
是的

**Comment by 1434205229** [comment]
差不多

**Comment by flyxuexi** [comment]
> 差不多

请问是在3090上训练的吗，epe能够到0.64或更低吗？我在4090上训练，epe收敛在了0.67....

**Comment by flyxuexi** [comment]
> 差不多

前辈，如果不冒犯的话，能加个联系方式吗，我的wx是fly007172，非常感谢

**Comment by 1434205229** [comment]
> > 差不多
> 
> 请问是在3090上训练的吗，epe能够到0.64或更低吗？我在4090上训练，epe收敛在了0.67....
我的是A6000 我当时可能也没到达0.64，具体不太记得了。没有到0.64你就多训练几回合就行。作者的意思是在sceneflow上训练20+20个epoch

**Comment by flyxuexi** [comment]
> > > 差不多
> > 
> > 
> > 请问是在3090上训练的吗，epe能够到0.64或更低吗？我在4090上训练，epe收敛在了0.67....
> > 我的是A6000 我当时可能也没到达0.64，具体不太记得了。没有到0.64你就多训练几回合就行。作者的意思是在sceneflow上训练20+20个epoch

好的谢谢
